title: 3<sup>S</sup> Research Group — Software Campus 2024
description: >-
  Software Campus 2024 projects at the Scalable Software Systems (3<sup>S</sup>) research group at Technische Universität Berlin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://3s-rg.github.io"

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme